[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "python -m amplpy.modules install scip",
  "python -m amplpy.modules activate $AMPL_LICENSE_UUID"
]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "hypercorn main:app --bind \"[::]:$PORT\""
